### ISSUE TITLE
Wrong path in libperfmgr/sepolicy.mk

### ISSUE THREAD

**Issue by dogpoopy** [Project-PixelStar/device_pixelstar_sepolicy#2]
This doesn't match the path where the repo has been cloned causing libperfmgr to break

https://github.com/Project-PixelStar/device_pixelstar_sepolicy/blob/896b25fa39cea44ca101b5b211225477c3deb97c/libperfmgr/sepolicy.mk#L2

https://github.com/Project-PixelStar/manifest/blob/36e3a6c1a4d929d666faafe56e42e4ff5809aae2/snippets/pixelstar.xml#L61

**Comment by Takixamru** [comment]
Hold On I am Working On It .
Thanks For Addressing The Issue
